# SPDX-FileCopyrightText: 2023 peirates-dev <peirates-dev@inguardians.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: gosec
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v3
      - name: Configure Dependencies
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -d
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-conf test/.gosec.config.json -track-suppressions ./...'

